wandb_version: 1

batch_size:
  desc: null
  value: 40
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 10
fc_layer_size1:
  desc: null
  value: 64
fc_layer_size2:
  desc: null
  value: 64
kernel_regularizer:
  desc: null
  value: 0.17359823438166697
learning_rate:
  desc: null
  value: 0.05598611175222931
optimizer:
  desc: null
  value: sgd
reccurent_dropout:
  desc: null
  value: 0.2
weight_decay:
  desc: null
  value: 0.0005
activation:
  desc: null
  value: relu
momentum:
  desc: null
  value: 0.9
seed:
  desc: null
  value: 42
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1702656089.051122
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 16
      - 23
      - 37
      4: 3.11.6
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      10:
      - 1
      - 9
      13: windows-amd64
