#ifndef PRE_DEFINED_PARAMS_H
#define PRE_DEFINED_PARAMS_H

#define DEVICE_CONNECT							0x01	//	The first required command.
#define DEVICE_DISCONNECT						0x02	//	The required command on user application exit.
#define GET_ERROR								0x03	//	CONNECTED STATE; DISCONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define GET_STATUS								0x04	//	CONNECTED STATE; EXECUTABLE IN IDLE MODE
#define START									0x05	//	CONNECTED STATE; EXECUTABLE IN IDLE MODE
#define GET_DATA								0x06	//	CONNECTED STATE; EXECUTABLE IN ACTIVE MODE
#define STOP									0x07	//	CONNECTED STATE; EXECUTABLE IN ACTIVE MODE
#define SET_SAMPLINGRATE_DIVIDER				0x08	//	CONNECTED STATE; EXECUTABLE IN IDLE MODE
#define SET_EXCITATION_LEVEL					0x09	//	CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define SET_INPUT_GAINS							0x0A	//	CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define SET_SUPPLY								0x0B	//	CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define GET_CONFIGURATION						0x0C	//	CONNECTED STATE; EXECUTABLE IN IDLE MODE
#define SET_GPIO								0x0D	//	CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define I2C_TRANSFER							0x0E	//	CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define SET_EXTERNAL_TRIGGER					0x0F	//	CONNECTED STATE; EXECUTABLE IN IDLE MODE _OR_ EXECUTABLE IN ACTIVE MODE

#define SET_SHUNT								0x10	//	CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define SET_COMP								0x11	//	CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define SET_COMPENSATION						0x12	//	CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define GET_GPIO								0x13	//	CONNECTED STATE; DISCONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define SELECT_10X_GAIN_ADC_CHANNELS			0x14	//  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define SET_DAC_VALS							0x16    //  CONNECTED STATE; EXECUTABLE IN IDLE MODE
#define SET_BMS_VALS							0x17	//  CONNECTED STATE; EXECUTABLE IN IDLE MODE
#define SET_BIN_FREQUENCIES						0x18	//  CONNECTED STATE; EXECUTABLE IN IDLE MODE								
#define SET_WINDOW_MAGNITUDE					0x19	//  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE	
#define SET_WINDOW_PHASE						0x1A	//  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE	
#define SET_WINDOW_FUNCTION						0x1B	//  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE	
#define SET_ADC_PHASE							0x1C	//  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE

#define MUX_GET_DATA							0x30    //  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define MUX_SET_DATA							0x31    //  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define MUX_SET_POSITION_MANUALLY				0x32    //  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define MUX_RESET								0x33    //  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define MUX_SELECT_TABLE						0x34    //  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define MUX_STEPPING_MODE						0x35    //  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define MUX_STEPPING_PERIOD						0x36    //  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define MUX_EEPROM_STORE_TABLE					0x37    //  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define MUX_EEPROM_TABLE_SIZE					0x41    //  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define MUX_SET_EXITATION_SOURCE				0x43    //  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define MUX_FRAM_TABLE_SIZE						0x44    //  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define MUX_FRAM_STORE_TABLE					0x45    //  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE
#define MUX_PAUSE_AFTER_CYCLE					0x49    //  CONNECTED STATE; EXECUTABLE IN IDLE MODE AND EXECUTABLE IN ACTIVE MODE

#endif // !PRE_DEFINED_PARAMS_H
