wandb_version: 1

batch_size:
  value: 40
dropout:
  value: 0.5
epochs:
  value: 10
fc_layer_size1:
  value: 64
fc_layer_size2:
  value: 64
kernel_regularizer:
  value: 0.17359823438166697
learning_rate:
  value: 0.05598611175222931
optimizer:
  value: sgd
reccurent_dropout:
  value: 0.2
