wandb_version: 1

batch_size:
  value: 240
dropout:
  value: 0.2
epochs:
  value: 10
fc_layer_size1:
  value: 64
fc_layer_size2:
  value: 128
kernel_regularizer:
  value: 0.19948965138089544
learning_rate:
  value: 0.036104912637769326
optimizer:
  value: sgd
reccurent_dropout:
  value: 0.2
