wandb_version: 1

batch_size:
  value: 40
dropout:
  value: 0.2
epochs:
  value: 10
fc_layer_size1:
  value: 256
fc_layer_size2:
  value: 128
kernel_regularizer:
  value: 0.04746555240121796
learning_rate:
  value: 0.08293745136781827
optimizer:
  value: nadam
reccurent_dropout:
  value: 0.2
